# 代码审计配置
code_audit:
  # 代码仓库路径
  repository_path: ""
  
  # AST缓存配置
  ast_cache:
    # 是否启用AST缓存
    enabled: true
    # AST缓存目录
    cache_dir: "./cache"
    # 是否在启动时重新构建AST（当enabled为true时，此选项生效）
    rebuild_on_startup: false

# 远程仓库配置
remote_repository:
  enabled: false
  type: ""  # zip, git, local
  url: ""
  branch: "main"
  target_path: "/tmp/fenrir_remote"
  auto_clean: true
